#!/bin/sh

# background
~/.fehbg

#autostart
nm-applet &
sxhkd &
dunst &
picom &

# monitor
if [ -n "$(xrandr -q | grep -w connected | grep HDMI-1)" ]; then
  bspc monitor HDMI-1 -d 1 2 3 4 5
  bspc monitor eDP-1 -d 6 7 8 9 10
  polybar primary & 
  polybar secondary & 
  xrandr --output HDMI-1 --right-of eDP-1
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  polybar mono  & 
fi

# config
bspc config window_gap 5
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# rules
bspc rule -a mumble state=floating follow=on focus=on

